"""Generate long-form research reports from wiki content."""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

from lore.config import OUTPUTS_DIR, WIKI_DIR
from lore.index.search import hybrid_search
from lore.compile.compiler import generate


def generate_report(topic: str) -> Path:
    """
    Generate a comprehensive research report on a topic.
    Queries the wiki from multiple angles, synthesizes into a report.
    """
    print(f"[render] Generating report: {topic}")
    outputs_dir = OUTPUTS_DIR / "reports"
    outputs_dir.mkdir(parents=True, exist_ok=True)

    # Multi-angle queries
    angles = [
        f"What is {topic}? Definition and overview.",
        f"What are the key techniques and methods in {topic}?",
        f"What are the recent advances and state of the art in {topic}?",
        f"What are the open problems and limitations in {topic}?",
        f"What are the most important papers in {topic}?",
        f"Who are the key researchers working on {topic}?",
    ]

    angle_results: list[tuple[str, str, list[str]]] = []  # (angle, answer, article_paths)
    all_paths: set[str] = set()

    for angle in angles:
        results = hybrid_search(angle, top_k=5)
        if not results:
            continue
        paths = [r.article_path for r in results]
        all_paths.update(paths)

        # Read top articles for this angle
        context_parts = []
        for r in results[:4]:
            full = (WIKI_DIR / r.article_path).read_text(encoding="utf-8", errors="replace")
            context_parts.append(f"=== {r.title} ===\n{full[:1500]}")

        context = "\n\n".join(context_parts)
        prompt = f"Wiki context:\n{context}\n\nQuestion: {angle}\nAnswer:"
        answer = generate(prompt)
        angle_results.append((angle, answer, paths))
        print(f"[render] Angle: {angle[:50]}... done")

    # Synthesize into final report
    now = datetime.now(timezone.utc)
    slug = re.sub(r"[^\w]+", "-", topic.lower())[:40]
    filename = f"{slug}-{now.strftime('%Y%m%d')}.md"
    output_path = outputs_dir / filename

    sections = []
    section_map = {
        0: "## Background",
        1: "## Core Techniques",
        2: "## Recent Advances",
        3: "## Open Problems",
        4: "## Key Papers",
        5: "## Key Researchers",
    }
    for i, (angle, answer, _) in enumerate(angle_results):
        header = section_map.get(i, f"## {angle}")
        sections.append(f"{header}\n\n{answer}")

    # Build sources list
    sources = sorted(all_paths)
    sources_section = "## Sources\n\n" + "\n".join(
        f"- [[{Path(p).stem.replace('-', ' ').title()}]]"
        for p in sources
    )

    report = f"""# Research Report: {topic}

*Generated: {now.strftime('%Y-%m-%d')} | Source: Personal Wiki*

## Executive Summary

*This report synthesizes wiki knowledge about {topic} across {len(all_paths)} articles.*

{chr(10).join(sections)}

{sources_section}

---
*Generated by the personal wiki system. Verify claims against source articles.*
"""

    output_path.write_text(report, encoding="utf-8")
    print(f"[render] Report saved: {output_path}")
    return output_path
